### ISSUE TITLE
Swap TODO items

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1216]
There were some in-progress TODO items from the Swap implementation that weren't completed prior to merge.

- [x] Record `swap_nft_value` as `asset::Id` rather than `Value` (since the amount is always `1`)
- [x] Rename `swap_nft_value_commitment` to `fee_commitment` to reflect that the `SwapClaim`'s only effect on the transaction value balance is contributing pre-committed fees
- [x] Include asset ID in witness data: https://github.com/penumbra-zone/penumbra/pull/1104/files#r925088722
- [x] Check format of Swap NFT asset ID (and other `SwapPlaintext` fields) in `SwapClaimProof` transparent proof
- [x] Fix `SwapClaimProof` value commitment integrity check: We want to check that the value_commitment is a commitment to f penumbra tokens, where f is the fee amount committed to by the swap nft's asset id.
- [x] #1266
- [x] Match transparent proof to ZK proof implementation by recording integer amounts for asset 1/asset 2 amounts rather than `Value` types
- [x] `value_fee: Value` -> `fee_amount: u64`
- [x] Need blinding factor for _each_ of t1/t2/fee
- [x] Remove `SWAP_TYPE`
- [x] Drop `swap::Error` enum and use `anyhow`
- [x] #1265
- [x] #1267
- [x] #1268
- [x] Remove `impl From<&SwapPlaintext> for Vec<u8> {`
- [x] Make `asset_1`/`asset_2` private to enforce `asset_1 < asset_2`
- [x] Make `to_bytes` private

More context here: https://github.com/penumbra-zone/penumbra/pull/1104
