### ISSUE TITLE
Release tracking issue: Governance

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1790]
A governance MVP consists of:

- proposal submission and withdrawal
- four kinds of proposal (signaling, emergency, parameter change, and DAO spend) and their implementations
- validator voting,
- delegator voting, and
- DAO interactions.

Penumbra proposals are controlled by a client-side state machine which burns and mints NFTs corresponding to the state of a proposal. There is no `NoWithVeto` vote, unlike in the Cosmos SDK; instead, there is a threshold of `No` votes (out of all total votes cast) which causes the proposal to be vetoed. This diagram shows the flow of a proposal from start to finish:

![Governance (light)](https://user-images.githubusercontent.com/597089/223178885-4c2d3880-5444-4987-a6dd-b2be3e9cbba8.svg#gh-light-mode-only)
![Governance (dark)](https://user-images.githubusercontent.com/597089/223178897-3a2b14c4-59da-4d6e-8585-486e3bfde188.svg#gh-dark-mode-only)

In the above, rounded grey boxes are _actions submitted by the proposal author_, rectangular colored boxes are _the state of the proposal on chain_, colored circles are _outcomes of voting_.

Completing governance is broken down into the following sequence of remaining work: 

## Initial cleanup

- [x] #1791
- [x] #1792

## Refactoring and changing current functionality

- [x] #1793

### Delegator voting (PR #1881)

- [x] #1882
- [x] #1794
- [x] #1879
- [x] #1795
- [x] #2027
- [x] #2028

### Cleanup and finishing tallying (PR #2055)

- [x] #1466
- [x] #1796
- [x] #1798
- [x] #1797
- [x] https://github.com/penumbra-zone/penumbra/issues/2060

## Validate parameter change proposals

- [x] https://github.com/penumbra-zone/penumbra/issues/1221
- [x] #2067
- [x] https://github.com/penumbra-zone/penumbra/issues/1160
- [x] https://github.com/penumbra-zone/penumbra/issues/1156

## Implement the DAO (PR #2072)

- [x] #1799
- [x] #1154 
- [x] #1153
- [x] #2073

## Allow DAO to interact with funding streams (also in PR #2072)

- [x] #1800
- [x] #1802

## Make chain halts sticky

- [x] #2085

## Supporting DAO interactions

- [x] #2076
- [x] #2077
- [x] #2080

## Cleanup and documentation

- [x] #2026 
- [x] #2090
- [ ] https://github.com/penumbra-zone/penumbra/issues/2488
- [x] https://github.com/penumbra-zone/penumbra/issues/2130

## IBC actions

- [x] https://github.com/penumbra-zone/penumbra/issues/2173
- [x] https://github.com/penumbra-zone/penumbra/issues/3024

## Testing and assurance
- [x] https://github.com/penumbra-zone/penumbra/issues/1823
- [ ] https://github.com/penumbra-zone/penumbra/issues/1345
- [ ] https://github.com/penumbra-zone/penumbra/issues/2105

## Further enhancements

- [x] #1966

**Comment by conorsch** [comment]
We're in a good position to close out the next ~3-4 items on the checklist via https://github.com/penumbra-zone/penumbra/pull/1881; but higher priority currently on unblocking Zpoken work, so this work might slip to a subsequent sprint.

**Comment by zbuc** [comment]
This has some subtasks that aren't marked V1, should they be?
