### ISSUE TITLE
Dex Implementation Tracking Issue

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#1836]
1. [ ] [Composition of AMMs (for routing)](https://github.com/penumbra-zone/penumbra/issues/1776)
2. [x] [Implement `Path` type for routing](https://github.com/penumbra-zone/penumbra/issues/1777)
3. [x] [Design indices for liquidity positions](https://github.com/penumbra-zone/penumbra/issues/1778)
4. [ ] [Implement routing](https://github.com/penumbra-zone/penumbra/issues/1722)
5. [ ] [Implement execution](https://github.com/penumbra-zone/penumbra/issues/1724)
6. [ ] [Implement arbitrage](https://github.com/penumbra-zone/penumbra/issues/1779)
7. [ ] [Implement liquidity management APIs](https://github.com/penumbra-zone/penumbra/issues/1725)
8. [ ] protocol.penumbra.zone documentation

Future work
- [x] #1942 
- [x] #1950
     
Reference: [Dex planning document](https://hackmd.io/rsgSwz3BQKuL0GrSF0LWXA?view)

**Comment by hdevalence** [comment]
Replacing by #1724

**Comment by erwanor** [comment]
Deleting this issue because it contains no information that isn't tracked in the actual tracking issue and clutters search results, and bugs the automatic sub-issue <> tracking issue tracking of #1724
