### ISSUE TITLE
Refactor pviewd to pclientd

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#1862]
# `pclientd`

## Motivation

Penumbra users should have a way of utilizing the view client code without needing to import our Rust libraries, which we can provide via an API providing a standard interface for other applications in any language to send requests to our client services and receive responses corresponding to transaction plans, authorization data, or confirmation of transaction submission. To distinguish this broader functionality from the existing view client code provided in `pviewd`, `pviewd` will be renamed to `pclientd`, as the “view” functionality will only be one mode of client operation, alongside a “custody” mode available when spend keys are provided to the component custody service.

`Pclientd` is a renaming and extension of the existing `pviewd` service, to better encapsulate its intended function as a client interface for distinct view and custody services. We want `pclientd` to provide endpoints that allow the client to serve requests for transaction plans, authorization data, and the building and proving of transactions, independently of the language of implementation of the software making these requests. 

By providing a GRPC service as an interface, any entity which provides a properly formatted RPC request to `pclientd` can receive an appropriate RPC response. `pclientd` will be initialized in either “view” or “custody” mode depending on the key material available, and will be accordingly able to serve requests. The further division of `pclientd` into components like a `PlannerService` and a `CustodyService` ensures that `pclientd` does not need to make assumptions about why a `TransactionPlan` or any `AuthorizationData` is being requested as long as the key material provided is sufficient to authorize the request.

## Sketch

Workflow:

- Initialization
    - `pclientd init view` -- takes an FVK
    - `pclientd init custody` -- takes a seed phrase (?)
    - No need to change modes post-initialization, if you want to change, re-initialize
- Running
    - `pclientd start` -- starts the service
    - Runs view protocol GRPC at all times
    - Runs custody protocol GRPC if key material is present
- Usage
    - consumer code makes a `PlannerRequest` to get a `TransactionPlan` (#1782)
    - consumer code sends the `TransactionPlan` in an `AuthorizeRequest` to custody service to get auth data
    - consumer code sends the `AuthorizationData` + `TransactionPlan` to new view service RPC method that builds and proves the `Transaction` 

## Custody service

- research tracked in #1863, custody service completed by #1873
- existing custody service implementation in the `SoftKms` structure in the custody crate
- should be reused
- needs to be extended to support pre-authorizations, so that accidentally exposing the port doesn't cause loss of funds
- needs a config format
    - toml?
    - needs a migration path from current format, used in `pcli`
    - in the future, we don't want `pcli` to hardcode use of `SoftKms`, so we want `pcli`'s custody format to be more general and support multiple backends

## Todo

- [ ] Rename `pviewd` binary instead of relocating it (code structure can be rearranged at some future point)
- [ ] Pull `SoftKms` from custody crate into `pclientd`
- [ ] Implement workflow described above
  - [ ] Binary will need a home directory for config file (similar to how `pd` or Tendermint work currently)
  - [ ] Define config struct for `pclientd` that includes the SoftKms config as a subsection
  - [ ] Change init logic to include toggle between `init view` or `init custody` startup modes
  - [ ] Change start logic to read the config values (ex. determine whether we should run SoftKms in addition to View service)
- [ ] We also need to actually build the transaction (#1883)

**Comment by conorsch** [comment]
See also https://github.com/penumbra-zone/penumbra/issues/1896, which will affect implementation here. Not blocked, OK to proceed, but won't make #1877.

**Comment by conorsch** [comment]
@aubrika is optimistic about a PR implementing much of the work here. Whether it's feature-complete, sufficient to close, we'll discuss during review.

**Comment by redshiftzero** [comment]
Closing as done
