### ISSUE TITLE
Epic: HTTPS support for all things Penumbra

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#1886]
We want an HTTPS-by-default story for all relevant Penumbra components. This epic tracks that work. The tickets are listed in approximate order of priority, and therefore intended order of implementation. 

* [ ] https://github.com/penumbra-zone/penumbra/issues/1766
* [ ] Add support for HTTPS calls via pcli
* [ ] Add support for HTTPS calls via pd during testnet join
* [ ] https://github.com/penumbra-zone/penumbra/issues/1405
* [ ] https://github.com/penumbra-zone/penumbra/issues/1406
* [ ] https://github.com/penumbra-zone/penumbra/issues/1727
* [ ] https://github.com/penumbra-zone/penumbra/issues/1728
* [ ] #1556 ; this may belong in its own epic, but we'll reprioritize as necessary

**Comment by cratelyn** [comment]
* #3119
