### ISSUE TITLE
Testnet 1 infrastructure checklist

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#193]
We should have:

- [x] a `testnet-001.penumbra.zone` subdomain pointing at a VPS running `pd`, `tendermint`, prometheus+grafana etc., with:
  - [x] the `pd` process's wallet port exposed to the outside world
  - [x] the `pd` process's ABCI port restricted to the local machine (so it can only be accessed by tendermint)
  - [x] the `tendermint` RPC port exposed to the outside world (in some safe way?)
  - [x] configuring grafana on port 80/443 with public access?

**Comment by kwf** [comment]
Testnet 1 will be named "valetudo", so the subdomain is `valetudo.penumbra.zone` rather than `testnet-001.penumbra.zone`.

**Comment by zbuc** [comment]
Exposed pd wallet port (26666) on `valetudo.penumbra.zone:26666`. The ABCI port (26658) is exposed only on the local machine.

All `tendermint` ports are currently exposed publicly (not sure if this is safe, but it's how the docker-compose.yml is currently configured!):

```
      - "26656-26657:26656-26657"
      - "6060:6060"
      - "27000:26660"
```

Grafana is exposed as well, albeit only on port 80. We have no SSL termination right now, potentially DigitalOcean has an SSL-terminating proxy we can use or we can add nginx to our stack and use Let's Encrypt certs?

**Comment by zbuc** [comment]
OK actually I was unable to figure out how to expose the `pd` ABCI port only to the local machine yet, it's currently publicly accessible:

```console
valetudo:~/penumbra# docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS          PORTS                                                                                                                                                             NAMES
f508380ee4d3   tendermint/tendermint    "docker-entrypoint.s…"   12 seconds ago   Up 10 seconds   0.0.0.0:6060->6060/tcp, :::6060->6060/tcp, 0.0.0.0:26656-26657->26656-26657/tcp, :::26656-26657->26656-26657/tcp, 0.0.0.0:27000->26660/tcp, :::27000->26660/tcp   tendermint
5426d616a677   penumbra_pd              "bash -c 'pd start -…"   12 seconds ago   Up 11 seconds   0.0.0.0:26658->26658/tcp, :::26658->26658/tcp, 0.0.0.0:26666->26666/tcp, :::26666->26666/tcp                                                                      penumbra
c3f608839289   grafana/grafana:latest   "/run.sh"                2 minutes ago    Up 2 minutes    0.0.0.0:80->3000/tcp, :::80->3000/tcp                                                                                                                             penumbra_grafana_1
000ed0e18963   prom/prometheus:latest   "/bin/prometheus --c…"   16 hours ago     Up 13 hours     0.0.0.0:9090->9090/tcp, :::9090->9090/tcp                                                                                                                         penumbra_prometheus_1
```

**Comment by zbuc** [comment]
TLS is up and running provided via Caddy and Let's Encrypt 🎉
