### ISSUE TITLE
Make checklist for each testnet release

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#210]
We should collect a list of all the places where things need to be changed every time a testnet is released, and ensure we follow this checklist every time we release a new testnet.

**Comment by redshiftzero** [comment]
There are a few notes in the repo README under the genesis section re: what needs to change in the genesis file for each testnet which can be removed or moved to this checklist when it exists:

> To perform genesis for a testnet, edit the genesis.json file stored in $TMHOME/config/ or ~/.tendermint/config/ (see an example in testnets/genesis_tn001.json). You should edit the following fields:

>    validators key: add the other validators and their voting power,
>    app_state key: add the generated genesis notes,
>    chain_id update the chain_id for the testnet.

**Comment by zbuc** [comment]
Where should this checklist exist, just as another Markdown file in the repo?

**Comment by redshiftzero** [comment]
One other item for the checklist is to `git tag 00X-name` such that if breaking changes are merged after the testnet is live, testers are not disrupted

**Comment by zbuc** [comment]
- [ ] Update hardcoded testnet URL in code
- [ ] Create new git tag e.g. `002-euporie`
- [ ] Create droplet & associated floating IP
- [ ] Add droplet to database trusted sources in DO
- [ ] Add team member SSH keys to droplet
- [ ] Create A record in Namecheap for testnet DNS
- [ ] Create database and credential in DO 
- [ ] Create database config file on droplet (`/root/secretz/db_connection_string`)
- [ ] Configure grafana (`/etc/grafana`)
