### ISSUE TITLE
Proposed `penumbra-crypto` code reorganization

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#2765]
This is a more detailed proposal for the final item in #2288. As described there, `penumbra-crypto` has become a catch-all crate for a bunch of diverse functionality. The scope of this ticket is to:

1. Rehome the various modules of `penumbra-crypto` to existing crates that make sense, or create new crates if needed, 
2. Remove code in `penumbra-crypto` we're not using, i.e. stuff that was originally targeted for Penumbra mainnet but will end up going into PenumbraV2, possibly with significant changes. 

## Concrete steps

Note that the following paths refer to the various modules in `penumbra-crypto` in `crates/core/crypto`.

- [x] Move `SwapFlow` (in `flow.rs`) to the `penumbra-dex` component. Remove `MockFlowCiphertext` and instead just use `Amount`s. This removes `flow.rs`. - #2766
- [x] Remove `eddy.rs` for now - we'll bring it back in the appropriate place if needed for PenumbraV2. - #2766
- [x] Move code in `governance*` to the `penumbra-governance` crate. Currently this crate doesn't exist, so in the meantime we could move it alongside where the governance component lives. Then this governance code would all be moved together to the `penumbra-governance` crate, as described/tracked in #2288. - https://github.com/penumbra-zone/penumbra/pull/2776
- [x] Move code in `stake*` to the `penumbra-stake` crate. - https://github.com/penumbra-zone/penumbra/pull/2770
- [x] Move `memo.rs` to the `penumbra-transaction` crate, since as of #1222 the memo is at the transaction level. - https://github.com/penumbra-zone/penumbra/pull/2773
- [x] Move `effect_hash.rs` and `transaction.rs` to the `penumbra-component` crate (we need to implement `EffectingHash` for component-specific actions in the component crates). - an attempt in #2779 that is failing CI, next attempt in #2798
- [x] Create new crate `penumbra-num` for `Amount` and `U128x128` types. - #2781
- [x] Move `asset*` to a new `penumbra-asset` crate, along with `Value` and `Balance` - #2781
- [x] Move `note_payload.rs`, `rseed.rs`, to `penumbra-shielded-pool` - #2795
- [x] For the proofs, we'll move each of the proofs to the appropriate component crate, as was already done for the `SwapProof` and `SwapClaimProof`. Specifically:
  - [x] `UndelegateClaim` goes to `penumbra-stake`, - https://github.com/penumbra-zone/penumbra/pull/2769 
  - [x] `Output`, `Spend`, `NullifierDerivation` goes to `penumbra-shielded-pool`, - #2792
  - [x] `DelegatorVote` goes to `penumbra-governance` - #2792
- [x] The proof _traits_ should go into `penumbra-proof-params`. The traits are used by the component crates, which already require the `penumbra-proof-params` to do proving and verification. - #2792
- [x] #2774
- [x] `nullifier.rs` would move to the `penumbra-sct` crate. - #2795
- [x] Create new crate `penumbra-keys` for the key hierarchy (`keys*`), addresses (`address*`), `prf.rs` (used for key derivation, and also by `Rseed` so we'd need to expose it), this requires some API changes: https://github.com/penumbra-zone/penumbra/pull/2791
- [x] Move symmetric keys to `penumbra-keys` - `symmetric.rs` operates on notes and memos, might need API changes here - #2795
- [x] At this point, `penumbra-crypto` should be empty, so we'd delete it. As a final step, the re-exported types `Fr, Fq` and `rdsa` will need to be imported directly from `decaf377` and `decaf377-rdsa`. - #2798

**Comment by conorsch** [comment]
Ticket still open to track cleanup, but we've largely achieved the reorg we wanted in advance of pending security audits. :tada:
