### ISSUE TITLE
Tracking issue: Penumbra-web foundations

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/penumbra#2902]
**_Overall Goal_**: Begin the first step of the [vision outlined in the wallet repo](https://github.com/penumbra-zone/wallet/issues/16). Focused on setting up the new repo (with all the new type safety checks) & migrating account setup code (refactoring alongside).

Breakdown:
- [ ] Create new repo `penumbra/web` with TurboRepo boilerplate.
  - [ ] Strictest `.tsconfig` config
  - [ ] Eslint rules
  - [ ] Prettier
- [ ] Github actions for PRs. Should run tests, lints & builds.
- [ ] Apps directory
   - [ ] Web app starter
   - [ ] Extension starter
- [ ] Package directory
  - [ ] UI
  - [ ] Accounts/custody code
- [ ] Integrate tailwind + radix-ui + shadcn/ui
- [ ] Testing
   - [ ] Unit testing
   - [ ] Component snapshot testing
- [ ] User can set up seed phrase (stored encrypted in indexdb)

At the end of this sprint, we should re-evaluate if this should be continue as a parallel workstream or start having zpoken oriented toward migration to this repo.
