### ISSUE TITLE
Tracking Issue: support IBC integration in Astria

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3125]
Astria is using the Penumbra stack to build their sequencer. They'd like to be IBC-enabled, and last Thursday we had a meeting about what would be required for them to integrate our IBC stack. We'd like to support them in this, but there will be some work required on both sides. This issue tracks that work.

Currently, our IBC stack has two parts:

- `ibc-types`, which just does common modeling for IBC data types and messages;
- `penumbra-ibc`, which implements IBC on top of the state model provided by `penumbra-storage` and the component system provided by `penumbra-component`.

Since moving to our own IBC stack as part of #2379, we've hoped to generalize Penumbra's IBC implementation, with the long-term goal of separating the IBC logic from the state access.  We've held off on doing it until there's a concrete user, to avoid building the wrong generalization.

However, supporting Astria doesn't require that all of that work, because Astria already uses (some of) the Penumbra stack, in particular `penumbra-storage` and (a tweaked version of) the `Component` trait in `penumbra-component`. Instead, we just need to break the dependency of `penumbra-ibc` on other Penumbra components and generalize it for Astria's use case:

- [ ] Add substore support to `penumbra-storage`
- [ ] Determine changes to the `Component` trait needed for Astria to use it directly
- [ ] Design a mechanism to allow dynamic `AppHandler`s in the IBC component
- [ ] Reverse dependency relationship between `penumbra-ibc` and `penumbra-shielded-pool`

**Comment by conorsch** [comment]
We've spoken with Astria out of band, and we have a few more weeks to get the necessary functionality in place. Related work such as #3131 is not shipping in Testnet 62 (#3123), but we plan to return to it soon.
