### ISSUE TITLE
Tracking Issue: summoning ceremony coordinator

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#3138]
This is a tracking issue for the summoning ceremony coordinator and client tooling (in pcli).

The needs here are split into basic functionality cutting across the lifecycle of the ceremony, and then the individual steps needed in the ceremony.

### Basics

- [x] https://github.com/penumbra-zone/penumbra/issues/3139 
- [x] https://github.com/penumbra-zone/penumbra/issues/3140
- [x] https://github.com/penumbra-zone/penumbra/issues/3141

### Functionalities

- [x] https://github.com/penumbra-zone/penumbra/issues/3156
- [x] https://github.com/penumbra-zone/penumbra/issues/3157
- [x] https://github.com/penumbra-zone/penumbra/issues/3158
- [x] #3159
- [x] #3160

### Additional Tasks

- [x] #3200 
- [x] #3189 
- [x] https://github.com/penumbra-zone/penumbra/issues/3202

**Comment by cronokirby** [comment]
In terms of prioritizing being able to test the actual code for phase2, one way of splitting things would be:
- Create full schemas for everything we need
- Instead of being able to run a phase1, simply allow initializing the root manually
- Implement the rest, which should work with in the same way as if a phase1 had been run, just with no contributions there

**Comment by conorsch** [comment]
Plan for Testnet 63 is to land all of the issues tracked in OP.

**Comment by redshiftzero** [comment]
closing as completed!
