### ISSUE TITLE
Tracking Issue: Fees

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#3290]
This issue captures the state of fees work.

### Complete
- [x] https://github.com/penumbra-zone/penumbra/issues/2970
- [x] https://github.com/penumbra-zone/penumbra/issues/3194

### Remaining
- [x] https://github.com/penumbra-zone/penumbra/issues/3153
- [ ] https://github.com/penumbra-zone/penumbra/issues/3164
- [ ] https://github.com/penumbra-zone/penumbra/issues/2972
- [ ] #3633

**Comment by aubrika** [comment]
Closed as duplicate of #3367
