### ISSUE TITLE
Tracking issue: Threshold Custody

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#3341]
This tracks the features we want to implement for a basic threshold custody backend for `pcli`.

- [x] https://github.com/penumbra-zone/penumbra/issues/3342
- [x] https://github.com/penumbra-zone/penumbra/issues/3444
- [x] https://github.com/penumbra-zone/penumbra/issues/3343
- [x] https://github.com/penumbra-zone/penumbra/issues/3344
- [x] https://github.com/penumbra-zone/penumbra/issues/3345
- [x] https://github.com/penumbra-zone/penumbra/issues/3346
- [x] https://github.com/penumbra-zone/penumbra/issues/3347

**Comment by redshiftzero** [comment]
Closing as completed
