### ISSUE TITLE
Provenance Tracking

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3349]
Clients need to be able to identify and track provenance of all of the funds they control. 

_Why this feature is required pre-mainnet_

This is important to support use cases like “where did these funds come from” and “who sent me money”. Because Penumbra is a shielded chain, if we do not design this capability in, it may not be possible at all. We need to think through the end-to-end data flow before mainnet, because we may need to make changes to the chain state to be able to track all 
the necessary information.

_What we need to implement_

- [ ] Add source information to SpendableNoteRecord
- [ ] Determine how to represent the source address — the AddressView can only represent a Penumbra address, but the source might be an address on another chain that did an ICS20 transfer
- [ ] Determine how the view server can obtain the source information during scanning
- [ ] Re-evaluate the design of the NoteSource — should it really be a “stuffed” hash?
