### ISSUE TITLE
Release tracking issue: IBC

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#3361]
- [ ] Assurance: security audit

Why this feature is required pre-mainnet
We must ensure that the IBC implementation is solid enough to be trusted with real-world funds. In particular, we want an audit of the IBC state machine. Additionally, we should perform internal testing of the following: host chain upgrades, counterparty chain upgrades, and timeouts. The host chain upgrades testing overlaps with the “upgrade” planning project. Additionally, we nearly have support for automated integration tests via interchaintest. 
What we need to implement
We need to finalize the IBC implementation so that it’s auditable. 
Then we need to engage an external team (most likely Informal Systems or Zellic) to perform the audit. 
The internal testing we can perform immediately, to get a better handle on feature completeness.
Try to exercise light client attacks and misbehavior, to confirm resistance to known attacks.

- [ ] Circuit breaker functionality

Why this feature is required pre-mainnet
We must ensure that we cannot ever transfer out more tokens than were transferred in, for a specific asset. If this ever happens, that’s a bug, and our software should refuse the action. This is known as “circuit-breaker functionality” for IBC. We currently have some of this functionality, but we need to solidify what we’re going to launch with and make sure we have that implemented. 
What we need to implement
https://github.com/penumbra-zone/penumbra/issues/981
We should also consider rate limits or similar logic, other than the standard balance checks.

- [ ] Governance support for IBC actions

Why this feature is required pre- mainnet
Subjecting IBC to governance is necessary for the IBC implementation on Penumbra to be suitable for handling real-world funds. N.B. this feature overlaps with the Governance and Upgrades planning projects.
What we need to implement
https://github.com/penumbra-zone/penumbra/issues/2173

- [ ] Tooling and client support for transfers

Why this feature is required pre-mainnet
In order for users to transfer real-world funds into Penumbra, tooling must exist that enables them to bridge assets, both in and out. Ideally, this support would be built into the web extension GUI. As a fallback, we can ensure that there’s requisite CLI tooling, but that would require working with external teams (for inbound to Penumbra).
What we need to implement
We should aim to support ICS20 withdrawals and deposits in the web extension. Withdrawals are the easier case to handle, since we don’t need to talk to other chains. For deposits, we hope that we can build out web extension functionality to pass transaction proposals to an external wallet, e.g. Kepler, to finalize and submit the transaction on the counterparty chain.

- [ ] Add fee support to relayers 

Why this feature is required pre-mainnet
We require fees for mainnet, so to support IBC on mainnet, relayers must be able to pay fees.
What we need to implement
We must add fees support to the two (2) relayers we support: penumbra-zone/hermes and cosmos/relayer.
