### ISSUE TITLE
shielded-pool: remove supply tracking from component

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#4018]
We want to remove supply tracking functionality from the shielded pool. In practice, this means delegating accounting (if needed) to components that need to call `mint_note` and removing the `SupplyWrite` trait.

The high-level plan:
- [ ] shielded-pool: remove supply increment from `mint_note`
- [ ] shielded-pool: remove `SupplyWrite` 
- [ ] staking: implement `ValidatorPoolTracker` for delegation tokens
- [ ] ibc: remove redundant supply tracking

We won't need to replace the Ics20 usage of `SupplyWrite` because it was 1/ broken 2/ redundant with the existing value balance rate-limit mechanism.

```rust=

pub trait ValidatorPoolRead: StateRead {
    pub fn get_validator_pool(&self, id: &IdentityKey) -> Option<Value>;
}

pub(crate) ValidatorPoolWrite: StateWrite {
    pub fn increase_validator_pool(&mut self, id: &IdentityKey, value: Value) -> Result<Value>;
    pub fn decrease_validator_pool(&mut self, id: &IdentityKey, value: Value) -> Result<Value>;
}
```

Adding the following state keys:

- `staking/validators/data/pool/balance/{id}` -> Amount
- `staking/chain/total_bonded` -> Amount
