### ISSUE TITLE
Tracking issue: Dutch auction support for Penumbra

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#4196]
This issue is tracking completion of Dutch Auction for Penumbra:

**Design doc and context:** https://hackmd.io/@hdevalence/B1RjyYJgR

**Implementation plan:**
We break the implementation into the following milestones:

| Milestone | Deliverable |
| -------- | -------- |
| Component M0 | Functional action handlers + basic RPC |
| Component M1 | Value balance accounting /  Full RPC + Events |
| `pcli` M0 | We can record / execute / retire auctions in CLI    |
| `pcli` M1 | We can pass high-level parameters we want users to specify (time pref) and generate multiple DAs |
| Prax M0     | Update protos, react views for signing, view server updates |
| Minifront M0     | UI for gradual Dutch auctions     |
| Explorer M0    | Page displaying a DA     |
| Explorer M1    | Listing DAs / integrate into pair view |

with the following dependency relations:

```mermaid
graph TD
  CM0(Component M0) --> CM1
  CM1(Component M1) --> EM0
  EM0(Explorer M0) --> EM1
  EM1(Explorer M1)
  CM0 --> PM0
  PM0(pcli M0) --> PM1
  PM1(pcli M1)
  PM0 --> PrM0
  PrM0(Prax M0)
  PrM0 --> MM0
  MM0(Minifront M0)
  PM1 -.- MM0

  style CM0 fill:#f9d4e5,stroke:#333,stroke-width:2px
  style PM0 fill:#f9d5e5,stroke:#333,stroke-width:2px
  style PrM0 fill:#f6cd61,stroke:#333,stroke-width:2px
  style MM0 fill:#fe8a71,stroke:#333,stroke-width:2px
```

Tracking issue:

## Component
**Component M0: to build a protocol MVP for DAs**
- [x] auction: create component crate scaffolding: events.rs / state_key.rs
- [x] auction: define proto scaffolding
- [x] #4206
    - [x] `AuctionId`
    - [x] `AuctionNft`
    - [x] `DutchAuctionDescription`
    - [x] `DutchAuctionState`
    - [x] `DutchAuction`
    - [x] `ActionDutchAuctionSchedule`
    - [x] `ActionDutchAuctionEnd`
    - [x] `ActionDutchAuctionWithdraw`
    - [x] `ActionDutchAuctionWithdrawView`
    - [x] `ActionDutchAuctionScheduleView`
- [x] #4212
    - Note: Prior to doing this, the actions shouldn't be added in the `Transaction` because they will lack the equivalent trait impl
- [x] #4211
    - [x] `ActionDutchAuctionSchedule`
    - [x] `ActionDutchAuctionEnd`
    - [x] `ActionDutchAuctionWithdraw`
- [x] #4240
- [x] #4219
- [x] #4226
- [x] #4228

**`pcli` M0: to exercise and fill in the RPC impls**
- [x] #4227
- [x] https://github.com/penumbra-zone/penumbra/issues/4251
- [x] #4241
- [x] #4242
    - [x] `pcli tx auction dutch schedule`
    - [x] `pcli tx auction dutch end`
    - [x] `pcli tx auction dutch withdraw`
- [x] #4243
    - [x] `pcli q auction id AUCTION_ID`
- [x] #4244
    - [x] `pcli v auction list [--include-inactive]`

**Component M1: complete core implementation and enable discoverability**
- [x] auction: add new actions to action reference in protocol spec
- [x] #4303
    - [x] `EventDutchAuctionScheduled`
    - [x] `EventDutchAuctionUpdated`
    - [x] `EventDutchAuctionEnded`
- [x] #4356
- [ ] #4268
- [ ] #4304
- [ ] auction: add high-level design of auction component to spec

**`pcli` M1: to lay the groundwork for minifront M0**
- [x] #4302

**Prax M0** (to be tracked in web repos - presented here for context)
- [x] prax: pull in new protos
- [x] prax: define react views for each auction actions:
    - [x] `ActionDutchAuctionSchedule`
    - [x] `ActionDutchAuctionEnd`
    - [x] `ActionDutchAuctionWithdraw`
- [x] prax: update view server for auctions
- [x] prax: add planner support

**Implementation strategy notes:**

1. **The Component M0 and `pcli` M0 milestones should be done together**, in keeping with our previous practice of using `pcli` as a testbed for new features. These should be done as soon as possible. Component functionality that doesn't affect the external action interfaces (e.g., value balance accounting, event emission, etc) can be deferred.

2. Note that `pcli` M1 is not in itself a valuable product feature; the only reason to do it is to be able to parallelize the work of automatic parameter selection for GDAs so that the Minifront M0 can adapt or copy it.

3. The proto package for the new component should be `v1alpha1`; this is still going to cause breaking proto changes because we'll add new `Transaction` fields that use the `v1alpha1` types and then break them to point at the new package, but this shouldn't cause problems because other software won't use them and the entire project will be completed in a short time horizon.

**Comment by hdevalence** [comment]
Note on the proto point: I think the right time to switch auction from v1alpha1 to v1 is after the M0 milestone

**Comment by TalDerei** [comment]
tracking prax / minifront in this [tracking issue](https://github.com/penumbra-zone/web/issues/942)

**Comment by cratelyn** [comment]
👋 hey there! would someone mind unassigning me from this issue? i no longer have permission to do so, and would like to clean this out of my "_assigned_" tab.
