### ISSUE TITLE
Tracking: basic multi-asset fee support

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4326]
**Is your feature request related to a problem? Please describe.**

Users should be able to pay fees in non-native tokens (at a higher price), so that they can use Penumbra just by sending funds into the shielded pool.

**Describe the solution you'd like**

- [ ] #4320 lays out basic multi-asset fee support at the protocol level, but leaves some threads dangling:
- [ ] Swap alt fee tokens into the native token prior to fee burn
- [ ] Add events for fees
- [ ] Change Rust view server to record alt gas prices
- [ ] Change Rust view server to report alt gas prices in RPC responses
- [ ] Add alt fee token support to `pcli`

**Additional context**

Description of the motivation and rationale can be found in #4320

**Comment by TalDerei** [comment]
Before the next sprint planning starts, should this be tagged?
