### ISSUE TITLE
tracking: indexer catchup

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#4750]
We want to implement basic indexing in order to get sufficient feature parity with existing dashboard implementations.

Below are a list of sub-issues, organized by dashboard and API area.

# Cuiloa
- [ ] https://github.com/penumbra-zone/penumbra/issues/4745
- [x] https://github.com/penumbra-zone/penumbra/issues/4746
- [ ] https://github.com/penumbra-zone/penumbra/issues/4747
- [ ] https://github.com/penumbra-zone/penumbra/issues/4749

# Dex-Explorer
- [x] https://github.com/penumbra-zone/penumbra/issues/4736
- [x] https://github.com/penumbra-zone/penumbra/issues/4737
- [x] https://github.com/penumbra-zone/penumbra/issues/4738
- [x] https://github.com/penumbra-zone/penumbra/issues/4739
- [x] https://github.com/penumbra-zone/penumbra/issues/4740
- [ ] https://github.com/penumbra-zone/penumbra/issues/4741
- [x] https://github.com/penumbra-zone/penumbra/issues/4742
- [x] https://github.com/penumbra-zone/penumbra/issues/4743
- [x] https://github.com/penumbra-zone/penumbra/issues/4744

**Comment by faddat** [comment]
makes tons of sense

**Comment by aubrika** [comment]
Closed as no longer reflective of planned work - we do not intend to continue work on Cuiloa or replacing the old dex explorer API - cf. #4883
