### ISSUE TITLE
Cyllene Testnet Tracking Issue

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#673]
This is a tracking issue for the release of the next Penumbra testnet, Cyllene. 

**Final pre-flight testing:** Monday, April 25 in the AM Eastern time
**Release and deployment:** Monday, April 25, noon ET / 9am PT

Please file bugs if you find them and associate them with the Cyllene testnet milestone. 

High-level plan:
- [x] Pre-release testing throughout this week (week of Apr 18-Apr 22, 2022)
- [x] Generate pre-flight test plan (here: https://github.com/penumbra-zone/penumbra/wiki/Testnet-Acceptance-Tests)
- [x] Prepare announcement / high-level description of changes:
  - [x] #672
  - [x] #655
  - [x] #649 
  - [x] #578 
  - [x] #664
- [x] Final pre-flight testing on Monday, fixing any bugs found
- [x] Deployment on Monday using the existing droplet

**Comment by zbuc** [comment]
I previously created this PR to include additional allocations for Galileo at genesis: https://github.com/penumbra-zone/penumbra/pull/654

**Comment by zbuc** [comment]
Includes:

https://github.com/penumbra-zone/penumbra/pull/672
https://github.com/penumbra-zone/penumbra/pull/655
https://github.com/penumbra-zone/penumbra/pull/649
https://github.com/penumbra-zone/penumbra/pull/578
