### ISSUE TITLE
Metrics dashboards for pd tracking task

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#829]
As Penumbra matures, metrics have become increasingly useful for monitoring testnet performance and debugging, in addition to public dashboards being a great way of showing off.

Currently we only collect metrics from tendermint. #815 added some scaffolding to support a common means of tracking custom metrics in pd, but it's not being used by any dashboards yet.

- [x] Ensure the prometheus port exposed by pd is serving our custom metrics correctly
- [x] Add some additional metrics to the codebase and corresponding dashboards (missed block counts by validator, transactions, validator counts by status, etc.)
- [x] Add documentation to the dev guide for committing dashboards back to the repo
- [x] Get grafana dashboards working on testnet-preview to create a tighter metrics/dashboard development cycle

**Comment by hdevalence** [comment]
I think something's not quite right with the prometheus/pd setup -- on `testnet.penumbra.zone`, there aren't any `penumbra_` metrics in the grafana picker, even though #815 added them.

**Comment by zbuc** [comment]
I think the prometheus data source isn't configured correctly, I'll take a look

**Comment by hdevalence** [comment]
@zbuc wrong port maybe?
```
  - job_name: 'Penumbra Daemon'
    scrape_interval: 10s
    scheme: http
    metrics_path: metrics
    static_configs:
      - targets: ['192.167.10.10:9096']
```
vs
```
        /// Bind the metrics endpoint to this port.
        #[structopt(short, long, default_value = "9000")]
        metrics_port: u16,
```

**Comment by zbuc** [comment]
Seems likely.

**Comment by hdevalence** [comment]
I edited `config/prometheus.yml` to set the port to 9000 and restarted prometheus, and now the `penumbra_` metrics show up.
